name: build-snapshot

on:
  workflow_dispatch:
  push:

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:     
  build-win:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest]
        lazarus-versions: [stable]
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Test 7-Zip
      run: ./.github/scripts/test.bat
