name: build-snapshot

on:
  pull_request:
  push:
    paths-ignore:
    - "README.md"
    branches:
      - master

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest]
        lazarus-versions: [stable]
    steps:
    - uses: actions/checkout@v2
    - name: Install Free Pascal
      uses: alexx2000/setup-fpc@master
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
    - name: Install Lazarus
      uses: actions/checkout@v3
      with:
            repository: 'fpc/Lazarus'
    - name: List directory
      run: make install
    - name: Build the Main Application
      run: fpc -h

