name: build-test

on:
  pull_request:
  push:
    paths-ignore:
    - "README.md"
    branches:
      - master
      - releases/*

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
#        operating-system: [ubuntu-18.04,ubuntu-latest,windows-latest]
        operating-system: [macos-latest]
        lazarus-versions: [stable]
    steps:
    - uses: actions/checkout@v2
#    - name: Install Lazarus
#      uses: gcarreno/setup-lazarus@v2.2.9
#      with:
#        lazarus-version: ${{ matrix.lazarus-versions }}
#        include-packages: "Synapse 40.1"
#    - name: Build the Main Application
#      run: lazbuild "src/lazaruswithgithubactions.lpi"
    - name: Deploy to Staging server
      run: 'echo "$SSH_PRIVATE_KEY" > hello && sftp -i hello -b ./.github/upload.txt $REMOTE_USER@$REMOTE_HOST'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
