name: build-snapshot

on:
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-mac:
    runs-on: macos-latest-arm64
    steps:    
    - name: Checkout source
      uses: actions/checkout@v4 
    
    - name: Prepare source
      run: sed -i -e "s|BOX_CLIENT_SECRET = '\*'|BOX_CLIENT_SECRET = '$BOX_CLIENT_SECRET'|g" src/resourceunit.pas
      env:
        BOX_CLIENT_SECRET: ${{ secrets.BOX_CLIENT_SECRET }}

    - name: Test
      run: uname -a

    - name: Deploy to snapshot server
      run: ./.github/scripts/upload.sh
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}       
